[package]
name = "rte-sys"
version = "20.11.0"
description = "FFI bindings to DPDK"
links = "dpdk"
build = "build/main.rs"
edition = "2021"

[build-dependencies]
bindgen = "0.59"
cc = "1.0"

pkg-config = "0.3"
